language: python
python: 2.7
dist: trusty
before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y linux-user-chroot
install:
        - pip install tox
script:
        - tox
